services:
 internal-gateway:
    container_name: internal-gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: internal-gateway:latest
    environment:
      PORT: ${PORT}
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      IDENTITY_SERVICE_URI: ${IDENTITY_SERVICE_URI}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - beaver-network

networks:
  beaver-network:
    external: true